

Import('env')


env.SharedLibrary('beatforcecdda',['cdda.c','cddb.c','debug.c','http.c','llist.c','osa.c'])


env.Alias(target = "install", source=env.Install(dir="/usr/share/beatforce/plugins/input/", 
               source="libbeatforcecdda.so"))