

Import('env');

if env['ui'] == 'sdltk':
        print "Using 'sdltk' as main user interface!"
        env.SConscript(['../lib/src/SConscript'])
        env.SConscript(['ui/sdltk/SConscript'])        
        env.Append(CCFLAGS = '-Isrc/ui/sdltk/')
        env.Append(CCFLAGS = '-Isrc')
        env.Append(CCFLAGS = '-I/usr/include/libxml2')
        env.Program('beatforce',
                [
                        'playlist.c',
                        'songdb.c',
                        'main.c',
                        'effect.c',
                        'player.c',
                        'mixer.c',
                        'debug.c',
                        'osa.c',
                        'audio_output.c',
                        'llist.c',
                        'ringbuffer.c',
                        'sampler.c',
                        'input.c',
                        'output.c',
                        'plugin.c',
                        'theme.c',
                        'configfile.c'
                ],
                        LIBS=['m','SDL','fftw3','SDL_image','xml2','ui','sdltk'],
                        LIBPATH=['/usr/lib/gtk/','../lib/src/','ui/sdltk'])      
elif env['ui'] == 'gtk':
        print "Using 'gtk' as main user interface!"
        env.SConscript(['ui/gtk/SConscript'])    
        env.Append(CCFLAGS = '-Isrc/ui/gtk/')
        env.Append(CCFLAGS = '-Isrc')
        env.Append(CCFLAGS = '-I/usr/include/libxml2')
        env.Append(CCFLAGS = '-I/usr/include/gtk-1.2')
        env.Append(CCFLAGS = '-I/usr/include/glib-1.2')
        env.Append(CCFLAGS = '-I/usr/lib/glib/include')
        env.Program('beatforce',
                [
                        'playlist.c',
                        'songdb.c',
                        'main.c',
                        'effect.c',
                        'player.c',
                        'mixer.c',
                        'debug.c',
                        'osa.c',
                        'audio_output.c',
                        'llist.c',
                        'ringbuffer.c',
                        'sampler.c',
                        'input.c',
                        'output.c',
                        'plugin.c',
                        'configfile.c'
                ],
                        LIBS=['m','SDL','fftw3','SDL_image','xml2','ui','gtk','gdk'],
                        LIBPATH=['/usr/lib/gtk/','ui/gtk/'])      
elif env['ui'] == 'qt':
        print "Using 'qt' as main user interface!"
        env.SConscript(['ui/qt/SConscript'])    
        env.Append(CCFLAGS = '-Isrc/ui/qt/')
        env.Append(CCFLAGS = '-Isrc')
        env.Append(CCFLAGS = '-I/usr/include/libxml2')
        env.Program('beatforce',
                [
                        'playlist.c',
                        'songdb.c',
                        'main.c',
                        'effect.c',
                        'player.c',
                        'mixer.c',
                        'debug.c',
                        'osa.c',
                        'audio_output.c',
                        'llist.c',
                        'ringbuffer.c',
                        'sampler.c',
                        'input.c',
                        'output.c',
                        'plugin.c',
                        'configfile.c'
                ],
                        LIBS=['m','SDL','fftw3','SDL_image','xml2','ui'],
                        LIBPATH=['/usr/lib/gtk/','ui/qt/'])      








